version: "3"

networks:
    default:

services:

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:1.18
        container_name: "redisManager"
        depends_on:
            - redis
        environment:
            - "ADMIN_USER=root"
            - "ADMIN_PASS=@123"
            
            - "REDIS_1_HOST=redis"
            - "REDIS_1_PORT=6379"
            - "REDIS_1_AUTH=@123"
            
            - "REDIS_2_HOST=redis_master_1"
            - "REDIS_2_PORT=6379"
            
            - "REDIS_3_HOST=redis_master_1_slave_1"
            - "REDIS_23_PORT=6379"
            
            - "REDIS_4_HOST=redis_master_2"
            - "REDIS_4_PORT=6379"
            
            - "REDIS_5_HOST=redis_master_2_slave_1"
            - "REDIS_5_PORT=6379"
            
            - "REDIS_6_HOST=redis_master_3"
            - "REDIS_6_PORT=6379"
            
            - "REDIS_7_HOST=redis_master_3_slave_1"
            - "REDIS_7_PORT=6379"
        links:
            - redis
        ports:
            - "4009:80"
        networks:
            - default

    redis:
        image: redis:alpine
        container_name: "redis"
        command: redis-server --requirepass @123
        ports:
            - 4010:6379
        networks:
            - default

    redis_master_1:
        image: redis:alpine
        container_name: "rm1"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
            #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_1-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4011:6379
        networks:
            - default

    redis_master_1_slave_1:
        image: redis:alpine
        container_name: "rm1s1"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
          #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_1_slave_1-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4012:6379
        networks:
            - default

    redis_master_2:
        image: redis:alpine
        container_name: "rm2"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
          #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_2-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4013:6379
        networks:
            - default

    redis_master_2_slave_1:
        image: redis:alpine
        container_name: "rm2s1"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
          #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_2_slave_1-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4014:6379
        networks:
            - default

    redis_master_3:
        image: redis:alpine
        container_name: "rm3"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
          #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_3-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4015:6379
        networks:
            - default

    redis_master_3_slave_1:
        image: redis:alpine
        container_name: "rm3s1"
        command: [
            "redis-server", "/usr/local/etc/redis/redis.conf",
          #"--requirepass ${REDIS_PASSWORD}"
        ]
        volumes:
            - ./redis/data/redis_master_3_slave_1-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 4016:6379
        networks:
            - default



