# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproduct_recommendations.proto\"I\n\x15RecommendationRequest\x12\x0e\n\x06userID\x18\x01 \x01(\x05\x12\x0e\n\x06\x63\x61t_id\x18\x02 \x01(\x05\x12\x10\n\x08per_page\x18\x03 \x01(\x05\"W\n\x1cProductRecommendationRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x03\x12\r\n\x05stock\x18\x05 \x01(\x05\"M\n\x1dProductRecommendationsRequest\x12,\n\x05items\x18\x01 \x03(\x0b\x32\x1d.ProductRecommendationRequest2X\n\x0fRecommendations\x12\x45\n\tRecommend\x12\x16.RecommendationRequest\x1a\x1e.ProductRecommendationsRequest\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_recommendations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOMMENDATIONREQUEST._serialized_start=33
  _RECOMMENDATIONREQUEST._serialized_end=106
  _PRODUCTRECOMMENDATIONREQUEST._serialized_start=108
  _PRODUCTRECOMMENDATIONREQUEST._serialized_end=195
  _PRODUCTRECOMMENDATIONSREQUEST._serialized_start=197
  _PRODUCTRECOMMENDATIONSREQUEST._serialized_end=274
  _RECOMMENDATIONS._serialized_start=276
  _RECOMMENDATIONS._serialized_end=364
# @@protoc_insertion_point(module_scope)
