image:
  name: docker/compose:latest

services:
  - docker:dind

stages:
  - test
  - deploy

run_backend_test:
    stage: test
    before_script:
      - cp .env.example .env
    script:
        - docker-compose up --build -d
        - sleep 30
        - docker-compose exec -T app sh -c "php artisan test --coverage"

deploy_backend:
    stage: deploy
    image: kroniak/ssh-client
    before_script:
      - chmod 400 $SSH_KEY
    script:
      - ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $SSH_KEY root@$SERVER_IP "
          cd cicd-laravel-test &&
          git pull &&
          docker compose up --build --scale app=10 -d"
        

