version: '3.1'

services:
  mongo:
    image: mongo:7.0
    ports:
      - 9065:27017
    volumes:
          - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '@123'

      
