version: '3.1'

services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - 9065:27017
    volumes:
          - /home/masoud/Projects/Learn/03-MongoDB/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 'masoudn'

      
