# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\"\x19\n\x08\x46Request\x12\r\n\x05token\x18\x01 \x01(\t\"6\n\x03Log\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tetime\x18\x03 \x01(\x03\x32\'\n\x06Logger\x12\x1d\n\x08LogStore\x12\t.FRequest\x1a\x04.Log0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FREQUEST._serialized_start=16
  _FREQUEST._serialized_end=41
  _LOG._serialized_start=43
  _LOG._serialized_end=97
  _LOGGER._serialized_start=99
  _LOGGER._serialized_end=138
# @@protoc_insertion_point(module_scope)
