version: "3"

networks:
  private:
  public:

services:

  webserver:
    image: nginx:stable-alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${APP_WORKING_DIR}
      - ${CONFIG_PATH}/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure
    depends_on:
      - app
    networks:
      - public

  app:
    build:
      context: ${CONFIG_PATH}
      dockerfile: dockerfile
    volumes:
      - ${APP_PATH}:${APP_WORKING_DIR}
      - ${CONFIG_PATH}/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ${CONFIG_PATH}/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ${CONFIG_PATH}/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    restart: on-failure
    networks:
      - private
      - public

  db:
    image: mysql:8.0
    volumes:
      - ${CONFIG_PATH}/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    restart: on-failure
    networks:
      - private

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: on-failure
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    networks:
      - private

 