FROM php:8.2-fpm-alpine

RUN apk add --no-cache linux-headers
RUN docker-php-ext-install sockets \
    && apk add libxml2-dev && docker-php-ext-install soap \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer \
    && apk add --update libzip-dev curl-dev \
    && docker-php-ext-install curl

RUN apk add --update --no-cache --virtual .build-dependencies $PHPIZE_DEPS\
    && apk add autoconf

RUN pecl install xdebug
RUN docker-php-ext-install pdo pdo_mysql
RUN apk add --update npm
WORKDIR /www/app

    
CMD sh -c " \
    # npm install && \
    composer install && \
    php artisan migrate &&\
    php artisan storage:link && \
    php artisan key:generate &&\
    npm run build &&\
    php artisan test --coverage && \
    php-fpm"
