version: "3"
networks:
    default:
services:

    mysql:
        image: mysql:8.0
        container_name: "LN_Mysql"
        tty: true
        ports:
            - "5523:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: learn
            MYSQL_USER: 'masoud'
            MYSQL_PASSWORD: '@123'
            MYSQL_ROOT_PASSWORD: '@123'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin:5.2.1
        container_name: "LN_Phpmyadmin"
        links:
            - mysql
        ports:
            - "5524:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_USER": 'masoud'
            PMA_PASSWORD: '@123'
            MYSQL_ROOT_PASSWORD: '@123'
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 500M
        networks:
            - default


