version: "3"
networks:
    default:
services:

    pgsql:
        image: postgres
        container_name: "pgsql_${PROJECT_NAME}"
        tty: true
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - "${POSTGRES_PERSIST_PATH}:/var/lib/postgresql"
            - "${POSTGRES_PERSIST_PATH}/data:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - default

    pgadmin:
        container_name: "pgadmin_${PROJECT_NAME}"
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        volumes:
            - ${PGADMIN_PERSIST_PATH}:/var/lib/pgadmin
        ports:
            - "${PGADMIN_PORT}:80"
        networks:
            - default

    mysql:
        image: mysql:latest
        container_name: "mysql_${PROJECT_NAME}"
        tty: true
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - "${MYSQL_PERSIST_PATH}:/var/lib/mysql"
        environment:
            MYSQL_DATABASE: ${MYSQL_DB}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin
        container_name: "phpmyadmin_${PROJECT_NAME}"
        links:
            - mysql
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_ARBITRARY: 1
            PMA_USER": ${PHPMYADMIN_USER}
            PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 500M
        networks:
            - default


